import json
import logging
from typing import List

from agents.base_agent import BaseAgent

logger = logging.getLogger(__name__)


class NarrativeGeneratorAgent(BaseAgent):
    """
    Step 3 of the pipeline.
    Takes HIGH and MEDIUM findings, produces the attorney brief.
    Only runs if confidence_floor_met is True — enforced by orchestrator.
    """

    def __init__(self):
        super().__init__("narrative_v1.txt")

    def run(self, findings: List[dict], tip_text: str) -> dict:
        """
        findings: HIGH + MEDIUM findings from FraudPatternAgent
        tip_text: original whistleblower narrative
        Returns attorney brief as structured JSON.
        """
        # Only surface HIGH and MEDIUM to the brief — LOW stays in DB for attorney review
        surfaced = [f for f in findings if f.get("severity") in ("HIGH", "MEDIUM")]

        if not surfaced:
            return {
                "case_title": "Insufficient Evidence",
                "executive_summary": "No HIGH or MEDIUM severity findings were identified.",
                "allegations": [],
                "recommended_next_steps": ["Gather additional documentation before proceeding."],
                "disclaimer": "FOR ATTORNEY REVIEW ONLY. This document was generated by an AI system and does not constitute legal advice.",
            }

        prompt = (
            self.prompt_template
            .replace("{findings}", json.dumps(surfaced, indent=2))
            .replace("{tip_text}", tip_text or "No whistleblower narrative provided.")
        )
        raw = self._call_llm(prompt, temperature=0.1)  # slight warmth for prose quality
        result = self._parse_json(raw)

        result["prompt_version"] = self.prompt_version
        result["model_version"] = self.model
        return result
